# Generated by Django 3.2.7 on 2021-09-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_profile_userprofile'),
        ('Post', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile'),
            preserve_default=False,
        ),
    ]
